sudo: false
language: go

go:
  - master

notifications:
  email: false

before_install:
  - go get -t -v ./...

before_script:
  - go get github.com/mattn/goveralls

script:
  - ./coverage.sh
  - goveralls

after_success:
  - bash <(curl -s https://codecov.io/bash)
